# Generated by Django 4.2 on 2025-02-10 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='artist_images')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('realase_year', models.DateField()),
                ('genre', models.CharField(choices=[('P', 'Pop'), ('O', 'Otro'), ('E', 'Eléctronica'), ('C', 'Clásico'), ('R', 'Rock')], max_length=30)),
                ('cover', models.ImageField(upload_to='album_images')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='album_manager.artist')),
            ],
        ),
    ]
