# Generated by Django 4.2 on 2025-02-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('P', 'Pop'), ('O', 'Otro'), ('E', 'Eléctronica'), ('R', 'Rock'), ('C', 'Clásico')], max_length=30),
        ),
    ]
