# Generated by Django 4.2 on 2025-02-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0002_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('R', 'Rock'), ('C', 'Clásico'), ('O', 'Otro'), ('E', 'Eléctronica'), ('P', 'Pop')], max_length=30),
        ),
    ]
